export type AgentScope = "spectator" | "manager" | "commish";
export type AgentTool = {
  id: string;
  title: string;
  description: string;
  scope: AgentScope;
  kind: "atomic" | "workflow" | "read";
  mutating: boolean;
};

function tool(
  id: string,
  title: string,
  description: string,
  scope: AgentScope,
  kind: AgentTool["kind"],
): AgentTool {
  return { id, title, description, scope, kind, mutating: kind !== "read" };
}

/**
 * Named league primitives an agent may call. Ids match `createServerFn` export
 * names in `src/lib/league/fns.ts` and `src/lib/data/fns.ts`. Tick / tickAllLeagues
 * are a cron clock, not tools — omit them.
 */
export const AGENT_TOOLS: AgentTool[] = [
  tool(
    "listMyLeagues",
    "List my leagues",
    "List leagues the signed-in user belongs to.",
    "spectator",
    "read",
  ),
  tool(
    "createLeague",
    "Create league",
    "Create a hosted league and take the first seat.",
    "commish",
    "workflow",
  ),
  tool(
    "deleteLeague",
    "Delete league",
    "Permanently delete a hosted league the signed-in user commissioners.",
    "commish",
    "atomic",
  ),
  tool(
    "exportLeague",
    "Export league",
    "Download a JSON backup of a hosted league the signed-in user commissioners.",
    "commish",
    "read",
  ),
  tool(
    "joinLeague",
    "Join league",
    "Join a league by invite code and claim a seat, plus allowlist if the commish seeded one.",
    "manager",
    "atomic",
  ),
  tool(
    "previewInvite",
    "Preview invite",
    "Preview a league from an invite code.",
    "spectator",
    "read",
  ),
  tool("getDesk", "Get desk", "Load the league desk for a week.", "spectator", "read"),
  tool("getEvents", "Get events", "Read the league event diary.", "spectator", "read"),
  tool(
    "getLeagueFacts",
    "Get league facts",
    "Load standing facts rolled up through a week.",
    "spectator",
    "read",
  ),
  tool(
    "getAgentContext",
    "Get agent context",
    "Seat, spendable FAAB, facts, recent events, and the tools in your scope.",
    "spectator",
    "read",
  ),
  tool(
    "getDraft",
    "Get draft",
    "Load the live draft board, queue, and clock.",
    "spectator",
    "read",
  ),
  tool(
    "getMockPool",
    "Get mock pool",
    "Load the scored mock-draft player pool.",
    "spectator",
    "read",
  ),
  tool(
    "startDraft",
    "Start draft",
    "Open the draft room and start the clock.",
    "commish",
    "atomic",
  ),
  tool(
    "makePick",
    "Make pick",
    "Draft the player on the clock for your seat.",
    "manager",
    "atomic",
  ),
  tool("queueAdd", "Queue add", "Add a player to your draft queue.", "manager", "atomic"),
  tool(
    "queueRemove",
    "Queue remove",
    "Remove a player from your draft queue.",
    "manager",
    "atomic",
  ),
  tool("queueReorder", "Queue reorder", "Replace your draft queue order.", "manager", "atomic"),
  tool("setAutodraft", "Set autodraft", "Toggle autodraft for your seat.", "manager", "atomic"),
  tool(
    "autoFillDraft",
    "Auto-fill draft",
    "Autopick remaining draft seats to completion.",
    "commish",
    "workflow",
  ),
  tool("startPlayer", "Start player", "Move a player into a starting slot.", "manager", "atomic"),
  tool("sitPlayer", "Sit player", "Bench a starter.", "manager", "atomic"),
  tool(
    "addDrop",
    "Add/drop",
    "Add a player, optionally dropping another, as a free agent or FAAB claim.",
    "manager",
    "workflow",
  ),
  tool("dropPlayer", "Drop player", "Drop a player from your roster.", "manager", "atomic"),
  tool(
    "previewImport",
    "Preview Sleeper import",
    "Preview a Sleeper league import.",
    "manager",
    "read",
  ),
  tool(
    "importLeague",
    "Import Sleeper league",
    "Import a Sleeper league into the ledger.",
    "commish",
    "workflow",
  ),
  tool(
    "previewEspn",
    "Preview ESPN import",
    "Preview an ESPN league import. Never log swid/espnS2; not for traces.",
    "commish",
    "read",
  ),
  tool(
    "importEspn",
    "Import ESPN league",
    "Import an ESPN league into the ledger. Never log swid/espnS2; not for traces.",
    "commish",
    "workflow",
  ),
  tool(
    "previewRebuild",
    "Preview rebuild",
    "Preview a paste/PDF rebuild of a historical league.",
    "commish",
    "read",
  ),
  tool(
    "importRebuild",
    "Import rebuild",
    "Commit a paste/PDF rebuild into the ledger.",
    "commish",
    "workflow",
  ),
  tool(
    "getSettings",
    "Get settings",
    "Load league settings and whether you are commish.",
    "spectator",
    "read",
  ),
  tool(
    "saveSettings",
    "Save settings",
    "Save scoring, slots, FAAB, playoffs, and betting knobs.",
    "commish",
    "workflow",
  ),
  tool(
    "claimRoster",
    "Claim roster",
    "Claim an open roster seat as your own (invite code required unless you are commish).",
    "manager",
    "atomic",
  ),
  tool(
    "listAllowlist",
    "List allowlist",
    "List emails allowed to join this league.",
    "commish",
    "read",
  ),
  tool(
    "addAllowlistEmail",
    "Add allowlist email",
    "Add an email to the league invite allowlist.",
    "commish",
    "atomic",
  ),
  tool(
    "removeAllowlistEmail",
    "Remove allowlist email",
    "Remove an email from the league invite allowlist.",
    "commish",
    "atomic",
  ),
  tool("getClaims", "Get claims", "List waiver claims visible to you.", "spectator", "read"),
  tool(
    "cancelClaim",
    "Cancel claim",
    "Withdraw one of your pending waiver claims.",
    "manager",
    "atomic",
  ),
  tool(
    "processWaivers",
    "Process waivers",
    "Run the waiver wire and award winning claims.",
    "commish",
    "workflow",
  ),
  tool(
    "advanceWeek",
    "Advance week",
    "Lock the week, settle, and roll the league forward.",
    "commish",
    "workflow",
  ),
  tool("getTrades", "Get trades", "List trades in the league.", "spectator", "read"),
  tool(
    "getTradablePicks",
    "Get tradable picks",
    "List picks that can still be traded.",
    "spectator",
    "read",
  ),
  tool(
    "proposeTrade",
    "Propose trade",
    "Propose a multi-asset trade between rosters.",
    "manager",
    "workflow",
  ),
  tool(
    "voteTrade",
    "Vote trade",
    "Accept or reject a trade you are party to.",
    "manager",
    "atomic",
  ),
  tool("cancelTradeFn", "Cancel trade", "Cancel a trade you proposed.", "manager", "atomic"),
  tool("getSchedule", "Get schedule", "Load the matchup schedule.", "spectator", "read"),
  tool(
    "saveWeekSchedule",
    "Save week schedule",
    "Set home/away pairs for one week.",
    "commish",
    "workflow",
  ),
  tool(
    "rebuildSchedule",
    "Rebuild schedule",
    "Rebuild the remaining regular-season schedule.",
    "commish",
    "workflow",
  ),
  tool(
    "getBook",
    "Get book",
    "Load the matchup book, lines, and your tickets.",
    "spectator",
    "read",
  ),
  tool("placeWager", "Place wager", "Stake FAAB on a spread or moneyline.", "manager", "atomic"),
  tool("pullWager", "Pull wager", "Withdraw a wager before the book closes.", "manager", "atomic"),
  tool("getPulse", "Get pulse", "NFL state, scoreboard, news, and trending.", "spectator", "read"),
  tool("getScores", "Get scores", "Scoreboard for a week.", "spectator", "read"),
  tool(
    "getGameSummary",
    "Get game summary",
    "Box score and plays for one NFL game.",
    "spectator",
    "read",
  ),
  tool(
    "getWeekStats",
    "Get week stats",
    "Raw weekly stats for a season/week.",
    "spectator",
    "read",
  ),
  tool(
    "getLiveWire",
    "Get live wire",
    "Live scoring leaders for the current week.",
    "spectator",
    "read",
  ),
  tool(
    "findSleeperUser",
    "Find Sleeper user",
    "Lookup a Sleeper user by query.",
    "spectator",
    "read",
  ),
  tool(
    "getLeagueBundle",
    "Get league bundle",
    "League header, rosters, and users.",
    "spectator",
    "read",
  ),
  tool(
    "getReceipt",
    "Get receipt",
    "One roster's week as facts: score, what was left on the bench, what the wire cost. Team names only.",
    "spectator",
    "read",
  ),
  tool(
    "getWeekBoard",
    "Get week board",
    "Every matchup in a league for a week, each side linked to its receipt.",
    "spectator",
    "read",
  ),
  tool(
    "getGameLines",
    "Get game lines",
    "Closing spread, total, moneylines, prices, result, and context for every NFL game of a season or week, from nflverse. 1999 to now.",
    "spectator",
    "read",
  ),
  tool(
    "getGameContext",
    "Get game context",
    "One NFL game by nflverse id: lines, result, rest, roof, surface, division, QBs, referee.",
    "spectator",
    "read",
  ),
  tool(
    "sampleGames",
    "Sample games",
    "The cohort language: games across seasons matching a filter (home dog, spread band, total band, division, rest edge, roof, weekday, teams). Agents describe the shape; code finds them.",
    "spectator",
    "read",
  ),
  tool(
    "evaluateBets",
    "Evaluate bets",
    "Grade a list of hypothetical bets (spread, total, moneyline) against results: win, loss, push, units at the odds taken, closing-line value. Pure arithmetic, no opinion.",
    "spectator",
    "read",
  ),
  tool(
    "summarizeRun",
    "Summarize run",
    "Record, ROI, break-even rate, max drawdown, streaks, and per-season splits for a graded run. Counts with n, never a verdict.",
    "spectator",
    "read",
  ),
  tool(
    "getSourceLedger",
    "Get source ledger",
    "Over a season: the lineup each open source would have set, scored on the box score, beside the roster's own. Which source to trust in this league.",
    "spectator",
    "read",
  ),
  tool("getMatchups", "Get matchups", "Matchup cards for a week.", "spectator", "read"),
  tool(
    "getTicks",
    "Get matchup ticks",
    "Per-minute projected finals / win % / spread samples for one matchup on a game day.",
    "spectator",
    "read",
  ),
  tool("getTeam", "Get team", "One roster's lineup and bench for a week.", "spectator", "read"),
  tool("getWire", "Get wire", "Free-agent and available player wire.", "spectator", "read"),
  tool("getActivity", "Get activity", "Transaction activity for a week.", "spectator", "read"),
  tool("getByeWeeks", "Get bye weeks", "NFL bye weeks for a season.", "spectator", "read"),
  tool(
    "getProjections",
    "Get projections",
    "Project a given player list for a week.",
    "spectator",
    "read",
  ),
  tool(
    "getWeekProjections",
    "Get week projections",
    "Starter and rostered projections for a week.",
    "spectator",
    "read",
  ),
  tool(
    "getOutlooks",
    "Get outlooks",
    "Rest-of-season outlooks for player ids.",
    "spectator",
    "read",
  ),
  tool(
    "getPlayerProfile",
    "Get player profile",
    "Player page payload: news, stats, outlook.",
    "spectator",
    "read",
  ),
  tool("getLeaders", "Get leaders", "Season leaders at a position.", "spectator", "read"),
  tool(
    "getPlayerSearch",
    "Get player search",
    "Search players by name and position.",
    "spectator",
    "read",
  ),
  tool("getRecap", "Get recap", "Week recap / dispatch copy.", "spectator", "read"),
  tool("getSources", "Get sources", "Probe upstream data sources.", "spectator", "read"),
  tool(
    "getAiSettings",
    "Get AI settings",
    "Load your saved AI provider/model config, masked — never returns the key.",
    "spectator",
    "read",
  ),
  tool(
    "saveAiSettings",
    "Save AI settings",
    "Save your AI provider, model, and API key (BYOK), encrypted at rest.",
    "spectator",
    "workflow",
  ),
  tool(
    "deleteAiSettings",
    "Delete AI settings",
    "Remove your saved AI key and provider config.",
    "spectator",
    "atomic",
  ),
  tool(
    "testAiSettings",
    "Test AI settings",
    "Test your saved AI key with a tiny round-trip call.",
    "spectator",
    "read",
  ),
  tool(
    "analyzeImport",
    "Analyze import",
    "Extract league settings from pasted text via the commissioner's AI key.",
    "commish",
    "read",
  ),
];
