/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DataRouteImport } from './routes/data'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ImportRouteImport } from './routes/import'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as ScoresRouteImport } from './routes/scores'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'
import { Route as LeagueLeagueIdRouteImport } from './routes/league/$leagueId'
import { Route as ScoresGameIdRouteImport } from './routes/scores_.$gameId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiLeagueTickRouteImport } from './routes/api/league/tick'
import { Route as LeagueLeagueIdIndexRouteImport } from './routes/league/$leagueId/index'
import { Route as LeagueLeagueIdActivityRouteImport } from './routes/league/$leagueId/activity'
import { Route as LeagueLeagueIdDraftRouteImport } from './routes/league/$leagueId/draft'
import { Route as LeagueLeagueIdMatchupsRouteImport } from './routes/league/$leagueId/matchups'
import { Route as LeagueLeagueIdMockRouteImport } from './routes/league/$leagueId/mock'
import { Route as LeagueLeagueIdRecapRouteImport } from './routes/league/$leagueId/recap'
import { Route as LeagueLeagueIdRosterRouteImport } from './routes/league/$leagueId/roster'
import { Route as LeagueLeagueIdSettingsRouteImport } from './routes/league/$leagueId/settings'
import { Route as LeagueLeagueIdStandingsRouteImport } from './routes/league/$leagueId/standings'
import { Route as LeagueLeagueIdTradesRouteImport } from './routes/league/$leagueId/trades'
import { Route as LeagueLeagueIdWireRouteImport } from './routes/league/$leagueId/wire'
import { Route as RLeagueIdIndexRouteImport } from './routes/r/$leagueId/index'
import { Route as LeagueLeagueIdPlayerPlayerIdRouteImport } from './routes/league/$leagueId/player/$playerId'
import { Route as LeagueLeagueIdTeamRosterIdRouteImport } from './routes/league/$leagueId/team/$rosterId'
import { Route as RLeagueIdWeekRosterIdRouteImport } from './routes/r/$leagueId/$week.$rosterId'
import { Route as LeagueLeagueIdMatchupWeekMatchupIdRouteImport } from './routes/league/$leagueId/matchup/$week/$matchupId'
import { Route as ApiOgRLeagueIdWeekRosterIdRouteImport } from './routes/api/og/r/$leagueId.$week.$rosterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const LeagueLeagueIdRoute = LeagueLeagueIdRouteImport.update({
  id: '/league/$leagueId',
  path: '/league/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresGameIdRoute = ScoresGameIdRouteImport.update({
  id: '/scores_/$gameId',
  path: '/scores/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeagueTickRoute = ApiLeagueTickRouteImport.update({
  id: '/api/league/tick',
  path: '/api/league/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdIndexRoute = LeagueLeagueIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const LeagueLeagueIdActivityRoute = LeagueLeagueIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const LeagueLeagueIdDraftRoute = LeagueLeagueIdDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const LeagueLeagueIdMatchupsRoute = LeagueLeagueIdMatchupsRouteImport.update({
  id: '/matchups',
  path: '/matchups',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const LeagueLeagueIdMockRoute = LeagueLeagueIdMockRouteImport.update({
  id: '/mock',
  path: '/mock',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const LeagueLeagueIdRecapRoute = LeagueLeagueIdRecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const LeagueLeagueIdRosterRoute = LeagueLeagueIdRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const LeagueLeagueIdSettingsRoute = LeagueLeagueIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const LeagueLeagueIdStandingsRoute = LeagueLeagueIdStandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const LeagueLeagueIdTradesRoute = LeagueLeagueIdTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const LeagueLeagueIdWireRoute = LeagueLeagueIdWireRouteImport.update({
  id: '/wire',
  path: '/wire',
  getParentRoute: () => LeagueLeagueIdRoute,
} as any)
const RLeagueIdIndexRoute = RLeagueIdIndexRouteImport.update({
  id: '/r/$leagueId/',
  path: '/r/$leagueId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdPlayerPlayerIdRoute =
  LeagueLeagueIdPlayerPlayerIdRouteImport.update({
    id: '/player/$playerId',
    path: '/player/$playerId',
    getParentRoute: () => LeagueLeagueIdRoute,
  } as any)
const LeagueLeagueIdTeamRosterIdRoute =
  LeagueLeagueIdTeamRosterIdRouteImport.update({
    id: '/team/$rosterId',
    path: '/team/$rosterId',
    getParentRoute: () => LeagueLeagueIdRoute,
  } as any)
const RLeagueIdWeekRosterIdRoute = RLeagueIdWeekRosterIdRouteImport.update({
  id: '/r/$leagueId/$week/$rosterId',
  path: '/r/$leagueId/$week/$rosterId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdMatchupWeekMatchupIdRoute =
  LeagueLeagueIdMatchupWeekMatchupIdRouteImport.update({
    id: '/matchup/$week/$matchupId',
    path: '/matchup/$week/$matchupId',
    getParentRoute: () => LeagueLeagueIdRoute,
  } as any)
const ApiOgRLeagueIdWeekRosterIdRoute =
  ApiOgRLeagueIdWeekRosterIdRouteImport.update({
    id: '/api/og/r/$leagueId/$week/$rosterId',
    path: '/api/og/r/$leagueId/$week/$rosterId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/data': typeof DataRoute
  '/docs': typeof DocsRouteWithChildren
  '/import': typeof ImportRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/players': typeof PlayersRoute
  '/scores': typeof ScoresRoute
  '/api/mcp': typeof ApiMcpRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteWithChildren
  '/scores/$gameId': typeof ScoresGameIdRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/league/tick': typeof ApiLeagueTickRoute
  '/league/$leagueId/activity': typeof LeagueLeagueIdActivityRoute
  '/league/$leagueId/draft': typeof LeagueLeagueIdDraftRoute
  '/league/$leagueId/matchups': typeof LeagueLeagueIdMatchupsRoute
  '/league/$leagueId/mock': typeof LeagueLeagueIdMockRoute
  '/league/$leagueId/recap': typeof LeagueLeagueIdRecapRoute
  '/league/$leagueId/roster': typeof LeagueLeagueIdRosterRoute
  '/league/$leagueId/settings': typeof LeagueLeagueIdSettingsRoute
  '/league/$leagueId/standings': typeof LeagueLeagueIdStandingsRoute
  '/league/$leagueId/trades': typeof LeagueLeagueIdTradesRoute
  '/league/$leagueId/wire': typeof LeagueLeagueIdWireRoute
  '/league/$leagueId/': typeof LeagueLeagueIdIndexRoute
  '/r/$leagueId/': typeof RLeagueIdIndexRoute
  '/league/$leagueId/player/$playerId': typeof LeagueLeagueIdPlayerPlayerIdRoute
  '/league/$leagueId/team/$rosterId': typeof LeagueLeagueIdTeamRosterIdRoute
  '/r/$leagueId/$week/$rosterId': typeof RLeagueIdWeekRosterIdRoute
  '/league/$leagueId/matchup/$week/$matchupId': typeof LeagueLeagueIdMatchupWeekMatchupIdRoute
  '/api/og/r/$leagueId/$week/$rosterId': typeof ApiOgRLeagueIdWeekRosterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/data': typeof DataRoute
  '/import': typeof ImportRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/players': typeof PlayersRoute
  '/scores': typeof ScoresRoute
  '/api/mcp': typeof ApiMcpRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/scores/$gameId': typeof ScoresGameIdRoute
  '/docs': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/league/tick': typeof ApiLeagueTickRoute
  '/league/$leagueId/activity': typeof LeagueLeagueIdActivityRoute
  '/league/$leagueId/draft': typeof LeagueLeagueIdDraftRoute
  '/league/$leagueId/matchups': typeof LeagueLeagueIdMatchupsRoute
  '/league/$leagueId/mock': typeof LeagueLeagueIdMockRoute
  '/league/$leagueId/recap': typeof LeagueLeagueIdRecapRoute
  '/league/$leagueId/roster': typeof LeagueLeagueIdRosterRoute
  '/league/$leagueId/settings': typeof LeagueLeagueIdSettingsRoute
  '/league/$leagueId/standings': typeof LeagueLeagueIdStandingsRoute
  '/league/$leagueId/trades': typeof LeagueLeagueIdTradesRoute
  '/league/$leagueId/wire': typeof LeagueLeagueIdWireRoute
  '/league/$leagueId': typeof LeagueLeagueIdIndexRoute
  '/r/$leagueId': typeof RLeagueIdIndexRoute
  '/league/$leagueId/player/$playerId': typeof LeagueLeagueIdPlayerPlayerIdRoute
  '/league/$leagueId/team/$rosterId': typeof LeagueLeagueIdTeamRosterIdRoute
  '/r/$leagueId/$week/$rosterId': typeof RLeagueIdWeekRosterIdRoute
  '/league/$leagueId/matchup/$week/$matchupId': typeof LeagueLeagueIdMatchupWeekMatchupIdRoute
  '/api/og/r/$leagueId/$week/$rosterId': typeof ApiOgRLeagueIdWeekRosterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/data': typeof DataRoute
  '/docs': typeof DocsRouteWithChildren
  '/import': typeof ImportRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/players': typeof PlayersRoute
  '/scores': typeof ScoresRoute
  '/api/mcp': typeof ApiMcpRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/league/$leagueId': typeof LeagueLeagueIdRouteWithChildren
  '/scores_/$gameId': typeof ScoresGameIdRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/league/tick': typeof ApiLeagueTickRoute
  '/league/$leagueId/activity': typeof LeagueLeagueIdActivityRoute
  '/league/$leagueId/draft': typeof LeagueLeagueIdDraftRoute
  '/league/$leagueId/matchups': typeof LeagueLeagueIdMatchupsRoute
  '/league/$leagueId/mock': typeof LeagueLeagueIdMockRoute
  '/league/$leagueId/recap': typeof LeagueLeagueIdRecapRoute
  '/league/$leagueId/roster': typeof LeagueLeagueIdRosterRoute
  '/league/$leagueId/settings': typeof LeagueLeagueIdSettingsRoute
  '/league/$leagueId/standings': typeof LeagueLeagueIdStandingsRoute
  '/league/$leagueId/trades': typeof LeagueLeagueIdTradesRoute
  '/league/$leagueId/wire': typeof LeagueLeagueIdWireRoute
  '/league/$leagueId/': typeof LeagueLeagueIdIndexRoute
  '/r/$leagueId/': typeof RLeagueIdIndexRoute
  '/league/$leagueId/player/$playerId': typeof LeagueLeagueIdPlayerPlayerIdRoute
  '/league/$leagueId/team/$rosterId': typeof LeagueLeagueIdTeamRosterIdRoute
  '/r/$leagueId/$week/$rosterId': typeof RLeagueIdWeekRosterIdRoute
  '/league/$leagueId/matchup/$week/$matchupId': typeof LeagueLeagueIdMatchupWeekMatchupIdRoute
  '/api/og/r/$leagueId/$week/$rosterId': typeof ApiOgRLeagueIdWeekRosterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/data'
    | '/docs'
    | '/import'
    | '/join'
    | '/login'
    | '/new'
    | '/players'
    | '/scores'
    | '/api/mcp'
    | '/docs/$slug'
    | '/league/$leagueId'
    | '/scores/$gameId'
    | '/docs/'
    | '/api/auth/$'
    | '/api/league/tick'
    | '/league/$leagueId/activity'
    | '/league/$leagueId/draft'
    | '/league/$leagueId/matchups'
    | '/league/$leagueId/mock'
    | '/league/$leagueId/recap'
    | '/league/$leagueId/roster'
    | '/league/$leagueId/settings'
    | '/league/$leagueId/standings'
    | '/league/$leagueId/trades'
    | '/league/$leagueId/wire'
    | '/league/$leagueId/'
    | '/r/$leagueId/'
    | '/league/$leagueId/player/$playerId'
    | '/league/$leagueId/team/$rosterId'
    | '/r/$leagueId/$week/$rosterId'
    | '/league/$leagueId/matchup/$week/$matchupId'
    | '/api/og/r/$leagueId/$week/$rosterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/data'
    | '/import'
    | '/join'
    | '/login'
    | '/new'
    | '/players'
    | '/scores'
    | '/api/mcp'
    | '/docs/$slug'
    | '/scores/$gameId'
    | '/docs'
    | '/api/auth/$'
    | '/api/league/tick'
    | '/league/$leagueId/activity'
    | '/league/$leagueId/draft'
    | '/league/$leagueId/matchups'
    | '/league/$leagueId/mock'
    | '/league/$leagueId/recap'
    | '/league/$leagueId/roster'
    | '/league/$leagueId/settings'
    | '/league/$leagueId/standings'
    | '/league/$leagueId/trades'
    | '/league/$leagueId/wire'
    | '/league/$leagueId'
    | '/r/$leagueId'
    | '/league/$leagueId/player/$playerId'
    | '/league/$leagueId/team/$rosterId'
    | '/r/$leagueId/$week/$rosterId'
    | '/league/$leagueId/matchup/$week/$matchupId'
    | '/api/og/r/$leagueId/$week/$rosterId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/data'
    | '/docs'
    | '/import'
    | '/join'
    | '/login'
    | '/new'
    | '/players'
    | '/scores'
    | '/api/mcp'
    | '/docs/$slug'
    | '/league/$leagueId'
    | '/scores_/$gameId'
    | '/docs/'
    | '/api/auth/$'
    | '/api/league/tick'
    | '/league/$leagueId/activity'
    | '/league/$leagueId/draft'
    | '/league/$leagueId/matchups'
    | '/league/$leagueId/mock'
    | '/league/$leagueId/recap'
    | '/league/$leagueId/roster'
    | '/league/$leagueId/settings'
    | '/league/$leagueId/standings'
    | '/league/$leagueId/trades'
    | '/league/$leagueId/wire'
    | '/league/$leagueId/'
    | '/r/$leagueId/'
    | '/league/$leagueId/player/$playerId'
    | '/league/$leagueId/team/$rosterId'
    | '/r/$leagueId/$week/$rosterId'
    | '/league/$leagueId/matchup/$week/$matchupId'
    | '/api/og/r/$leagueId/$week/$rosterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  DataRoute: typeof DataRoute
  DocsRoute: typeof DocsRouteWithChildren
  ImportRoute: typeof ImportRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  PlayersRoute: typeof PlayersRoute
  ScoresRoute: typeof ScoresRoute
  ApiMcpRoute: typeof ApiMcpRoute
  LeagueLeagueIdRoute: typeof LeagueLeagueIdRouteWithChildren
  ScoresGameIdRoute: typeof ScoresGameIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiLeagueTickRoute: typeof ApiLeagueTickRoute
  RLeagueIdIndexRoute: typeof RLeagueIdIndexRoute
  RLeagueIdWeekRosterIdRoute: typeof RLeagueIdWeekRosterIdRoute
  ApiOgRLeagueIdWeekRosterIdRoute: typeof ApiOgRLeagueIdWeekRosterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/league/$leagueId': {
      id: '/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof LeagueLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores_/$gameId': {
      id: '/scores_/$gameId'
      path: '/scores/$gameId'
      fullPath: '/scores/$gameId'
      preLoaderRoute: typeof ScoresGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/league/tick': {
      id: '/api/league/tick'
      path: '/api/league/tick'
      fullPath: '/api/league/tick'
      preLoaderRoute: typeof ApiLeagueTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId/': {
      id: '/league/$leagueId/'
      path: '/'
      fullPath: '/league/$leagueId/'
      preLoaderRoute: typeof LeagueLeagueIdIndexRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/activity': {
      id: '/league/$leagueId/activity'
      path: '/activity'
      fullPath: '/league/$leagueId/activity'
      preLoaderRoute: typeof LeagueLeagueIdActivityRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/draft': {
      id: '/league/$leagueId/draft'
      path: '/draft'
      fullPath: '/league/$leagueId/draft'
      preLoaderRoute: typeof LeagueLeagueIdDraftRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/matchups': {
      id: '/league/$leagueId/matchups'
      path: '/matchups'
      fullPath: '/league/$leagueId/matchups'
      preLoaderRoute: typeof LeagueLeagueIdMatchupsRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/mock': {
      id: '/league/$leagueId/mock'
      path: '/mock'
      fullPath: '/league/$leagueId/mock'
      preLoaderRoute: typeof LeagueLeagueIdMockRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/recap': {
      id: '/league/$leagueId/recap'
      path: '/recap'
      fullPath: '/league/$leagueId/recap'
      preLoaderRoute: typeof LeagueLeagueIdRecapRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/roster': {
      id: '/league/$leagueId/roster'
      path: '/roster'
      fullPath: '/league/$leagueId/roster'
      preLoaderRoute: typeof LeagueLeagueIdRosterRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/settings': {
      id: '/league/$leagueId/settings'
      path: '/settings'
      fullPath: '/league/$leagueId/settings'
      preLoaderRoute: typeof LeagueLeagueIdSettingsRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/standings': {
      id: '/league/$leagueId/standings'
      path: '/standings'
      fullPath: '/league/$leagueId/standings'
      preLoaderRoute: typeof LeagueLeagueIdStandingsRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/trades': {
      id: '/league/$leagueId/trades'
      path: '/trades'
      fullPath: '/league/$leagueId/trades'
      preLoaderRoute: typeof LeagueLeagueIdTradesRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/wire': {
      id: '/league/$leagueId/wire'
      path: '/wire'
      fullPath: '/league/$leagueId/wire'
      preLoaderRoute: typeof LeagueLeagueIdWireRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/r/$leagueId/': {
      id: '/r/$leagueId/'
      path: '/r/$leagueId'
      fullPath: '/r/$leagueId/'
      preLoaderRoute: typeof RLeagueIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId/player/$playerId': {
      id: '/league/$leagueId/player/$playerId'
      path: '/player/$playerId'
      fullPath: '/league/$leagueId/player/$playerId'
      preLoaderRoute: typeof LeagueLeagueIdPlayerPlayerIdRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/league/$leagueId/team/$rosterId': {
      id: '/league/$leagueId/team/$rosterId'
      path: '/team/$rosterId'
      fullPath: '/league/$leagueId/team/$rosterId'
      preLoaderRoute: typeof LeagueLeagueIdTeamRosterIdRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/r/$leagueId/$week/$rosterId': {
      id: '/r/$leagueId/$week/$rosterId'
      path: '/r/$leagueId/$week/$rosterId'
      fullPath: '/r/$leagueId/$week/$rosterId'
      preLoaderRoute: typeof RLeagueIdWeekRosterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId/matchup/$week/$matchupId': {
      id: '/league/$leagueId/matchup/$week/$matchupId'
      path: '/matchup/$week/$matchupId'
      fullPath: '/league/$leagueId/matchup/$week/$matchupId'
      preLoaderRoute: typeof LeagueLeagueIdMatchupWeekMatchupIdRouteImport
      parentRoute: typeof LeagueLeagueIdRoute
    }
    '/api/og/r/$leagueId/$week/$rosterId': {
      id: '/api/og/r/$leagueId/$week/$rosterId'
      path: '/api/og/r/$leagueId/$week/$rosterId'
      fullPath: '/api/og/r/$leagueId/$week/$rosterId'
      preLoaderRoute: typeof ApiOgRLeagueIdWeekRosterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface LeagueLeagueIdRouteChildren {
  LeagueLeagueIdActivityRoute: typeof LeagueLeagueIdActivityRoute
  LeagueLeagueIdDraftRoute: typeof LeagueLeagueIdDraftRoute
  LeagueLeagueIdMatchupsRoute: typeof LeagueLeagueIdMatchupsRoute
  LeagueLeagueIdMockRoute: typeof LeagueLeagueIdMockRoute
  LeagueLeagueIdRecapRoute: typeof LeagueLeagueIdRecapRoute
  LeagueLeagueIdRosterRoute: typeof LeagueLeagueIdRosterRoute
  LeagueLeagueIdSettingsRoute: typeof LeagueLeagueIdSettingsRoute
  LeagueLeagueIdStandingsRoute: typeof LeagueLeagueIdStandingsRoute
  LeagueLeagueIdTradesRoute: typeof LeagueLeagueIdTradesRoute
  LeagueLeagueIdWireRoute: typeof LeagueLeagueIdWireRoute
  LeagueLeagueIdIndexRoute: typeof LeagueLeagueIdIndexRoute
  LeagueLeagueIdPlayerPlayerIdRoute: typeof LeagueLeagueIdPlayerPlayerIdRoute
  LeagueLeagueIdTeamRosterIdRoute: typeof LeagueLeagueIdTeamRosterIdRoute
  LeagueLeagueIdMatchupWeekMatchupIdRoute: typeof LeagueLeagueIdMatchupWeekMatchupIdRoute
}

const LeagueLeagueIdRouteChildren: LeagueLeagueIdRouteChildren = {
  LeagueLeagueIdActivityRoute: LeagueLeagueIdActivityRoute,
  LeagueLeagueIdDraftRoute: LeagueLeagueIdDraftRoute,
  LeagueLeagueIdMatchupsRoute: LeagueLeagueIdMatchupsRoute,
  LeagueLeagueIdMockRoute: LeagueLeagueIdMockRoute,
  LeagueLeagueIdRecapRoute: LeagueLeagueIdRecapRoute,
  LeagueLeagueIdRosterRoute: LeagueLeagueIdRosterRoute,
  LeagueLeagueIdSettingsRoute: LeagueLeagueIdSettingsRoute,
  LeagueLeagueIdStandingsRoute: LeagueLeagueIdStandingsRoute,
  LeagueLeagueIdTradesRoute: LeagueLeagueIdTradesRoute,
  LeagueLeagueIdWireRoute: LeagueLeagueIdWireRoute,
  LeagueLeagueIdIndexRoute: LeagueLeagueIdIndexRoute,
  LeagueLeagueIdPlayerPlayerIdRoute: LeagueLeagueIdPlayerPlayerIdRoute,
  LeagueLeagueIdTeamRosterIdRoute: LeagueLeagueIdTeamRosterIdRoute,
  LeagueLeagueIdMatchupWeekMatchupIdRoute:
    LeagueLeagueIdMatchupWeekMatchupIdRoute,
}

const LeagueLeagueIdRouteWithChildren = LeagueLeagueIdRoute._addFileChildren(
  LeagueLeagueIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  DataRoute: DataRoute,
  DocsRoute: DocsRouteWithChildren,
  ImportRoute: ImportRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  PlayersRoute: PlayersRoute,
  ScoresRoute: ScoresRoute,
  ApiMcpRoute: ApiMcpRoute,
  LeagueLeagueIdRoute: LeagueLeagueIdRouteWithChildren,
  ScoresGameIdRoute: ScoresGameIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiLeagueTickRoute: ApiLeagueTickRoute,
  RLeagueIdIndexRoute: RLeagueIdIndexRoute,
  RLeagueIdWeekRosterIdRoute: RLeagueIdWeekRosterIdRoute,
  ApiOgRLeagueIdWeekRosterIdRoute: ApiOgRLeagueIdWeekRosterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
